name: Tests

on:
  push:
    paths-ignore: [ '**.md' ]
  pull_request:
    paths-ignore: [ '**.md' ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      clickhouse:
        image: yandex/clickhouse-server
        ports: [ '8123:8123' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --extras orjson
      - name: Tests
        run: poetry run pytest --cov=pych_client --cov-report=xml
      - uses: codecov/codecov-action@v2
